
---
- name: Configure Web Server
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create webteam group
      group:
        name: webteam
        state: present

    - name: Create webadmin user
      user:
        name: webadmin
        groups: webteam
        append: yes
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Create developer user
      user:
        name: developer
        groups: webteam
        append: yes
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Create readonly user
      user:
        name: readonly
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Create /var/www/html directory
      file:
        path: /var/www/html
        state: directory
        owner: webadmin
        group: webteam
        mode: '0755'

    - name: Deploy custom index.html
      copy:
        dest: /var/www/html/index.html
        owner: webadmin
        group: webteam
        mode: '0644'
        content: |
          <html>
          <head><title>DevOps Project</title></head>
          <body>
          <h1>Infrastructure Platform</h1>
          <p>Engineer: Bollah Mariame</p>
          <p>Date: {{ ansible_date_time.date }}</p>
          <p>Tools: Terraform, Ansible, Docker</p>
          </body>
          </html>

    - name: Create /opt/scripts directory
      file:
        path: /opt/scripts
        state: directory
        mode: '0755'

    - name: Deploy health check script
      copy:
        dest: /opt/scripts/health_check.sh
        mode: '0755'
        content: |
          #!/bin/bash
          TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
          LOG="/var/log/health_check.log"
          if curl -sf http://localhost > /dev/null; then
            echo "$TIMESTAMP OK - Nginx is up" >> $LOG
          else
            echo "$TIMESTAMP FAIL - Nginx is down" >> $LOG
          fi

    - name: Schedule health check every 5 minutes
      cron:
        name: "Health check"
        minute: "*/5"
        job: "/opt/scripts/health_check.sh"

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted

    - name: Verify Nginx is responding
      uri:
        url: http://localhost
        status_code: 200















# ---
# - name: Configure Web Server
#   hosts: all
#   become: yes

#   vars:
#     docker_image: "tawa123/infrastructure-platform"
#     docker_tag: "latest"
#     container_name: "infrastructure-platform"

#   tasks:
#     - name: Update apt cache
#       apt:
#         update_cache: yes

#     - name: Install Ngnix
#       apt:
#         name: nginx
#         state: present

#     - name: Start and enable Ngnix
#       service: 
#         name: ngnix
#         state: started
#         enabled: yes    

#     - name: Create webteam group
#       group:
#         name: webteam
#         state: present

#     - name: Create webadmin user
#       user:
#         name: webadmin
#         state: present    

#     - name: Create developer user
#       user: 
#         name: developer
#         state: present       

#     - name: Create readonly user
#       user:
#         name: readonly
#         state: present    

#     - name: Create /var/www/html directory
#       file: 
#          path: /var/www/html
#          state: directory
#          owner: webadmin
#          group: webteam
#          mode: '0755'  

#     - name: Deploy custom index.html
#       copy:
#         dest: /var/www/html
#         content: 
#            <html>
#           <head><title>DevOps Project</title></head>
#           <body>
#           <h1> Infrastructure Platform </h1>
#           <p>Date: {{ ansible_date_time.date }}</p>
#           <p>Tools: Terraform, Ansible, Docker</p>
#           </body>
#           </html>

#     - name: Set ownership of index.html
#       file:
#         path: /var/www/html
#         owner: webadmin
#         group: webteam

#     - name: Create /opt/scripts directory
#       file: 
#          path: /opt/scripts
#          state: directory
#          mode: '0755'

#     - name: Deploy health check script
#       copy:
#         dest: /opt/scripts/health_check.sh
#         mode: '0755'
#         content: |
#           #!/bin/bash
#           curl -f http://localhost || echo "Service down"    

#     - name: Schedule health check every 5 minutes
#       cron:
#         name: "Health check"
#         minutes: "*/5"             
#         job: "/opt/script/health_check.sh"        
                

#     - name: Disable root login
#       lineinfile:
#         path: /etc/ssh/sshd_config
#         regexp: '^PermitRootLogin'
#         line: 'PermitRootLogin no' 

#     - name: Disable password authentication
#       lineinfile:
#          path: /etc/ssh/sshd_config
#          regexp: '^PasswordAuthentication' 
#          line: "PasswordAuthentication no"   

#     - name: Restart SSh service
#       service: 
#         name: SSh
#         state: restarted

#     - name: Verify Nginx is responding
#       uri:
#         url: http://localhost
#         status_code: 200  
                   